[package]
name = "pachislo"
version = "0.3.1"
edition = "2024"
description = "Pachislo game simulator"
repository = "https://github.com/kimuti-tsukai/pachislo"
authors = ["kimuti_tsukai <ruster354@gmail.com>"]
readme = "README.md"
license = "MIT"

[dependencies]
rand = "0.9.1"
